/*
 * Sortable viewer for the developer portfolios list.
 *
 * Loads feed.json (generated by src/generate_feed.py) and lets visitors pick
 * how the list is ordered. The comparators mirror src/portfolio_sorting.py:
 *
 *   name     alphabetical (case-insensitive)
 *   newest   date_added descending, entries without a date last
 *   popular  popularity score descending (explicit popularity, else views + clicks)
 *   views    views descending, then clicks descending
 *
 * Ties fall back to alphabetical order so results are deterministic.
 */
"use strict";

const FEED_URL = new URL("../feed.json", window.location.href);
const PAGE_SIZE = 60;
const STORAGE_KEY = "developer-portfolios:sort";
const SORT_OPTIONS = ["name", "newest", "popular", "views"];

const els = {
  totalCount: document.getElementById("total-count"),
  sortSelect: document.getElementById("sort-select"),
  status: document.getElementById("status"),
  metricsNote: document.getElementById("metrics-note"),
  error: document.getElementById("error"),
  list: document.getElementById("portfolio-list"),
  sentinel: document.getElementById("sentinel"),
};

let portfolios = [];
let sorted = [];
let renderedCount = 0;
let currentSort = "name";

/* ----------------------------- value helpers ----------------------------- */

function toNumber(value) {
  if (value === null || value === undefined || typeof value === "boolean") {
    return 0;
  }
  const number = typeof value === "number" ? value : Number.parseFloat(value);
  return Number.isFinite(number) ? number : 0;
}

function parseAddedDate(value) {
  if (typeof value === "number") {
    const fromEpoch = new Date(value * 1000);
    return Number.isNaN(fromEpoch.getTime()) ? null : fromEpoch;
  }
  if (typeof value !== "string") {
    return null;
  }
  const text = value.trim();
  if (!text) {
    return null;
  }
  const isoDate = /^(\d{4})-(\d{2})-(\d{2})/.exec(text);
  const parsed = isoDate
    ? new Date(`${isoDate[1]}-${isoDate[2]}-${isoDate[3]}T00:00:00Z`)
    : new Date(text);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

function nameKey(entry) {
  return String(entry.name || "").toLocaleLowerCase();
}

function popularityScore(entry) {
  if (entry.popularity !== null && entry.popularity !== undefined) {
    return toNumber(entry.popularity);
  }
  return toNumber(entry.views) + toNumber(entry.clicks);
}

function safeUrl(value) {
  try {
    const url = new URL(String(value), window.location.href);
    return url.protocol === "http:" || url.protocol === "https:" ? url.href : null;
  } catch {
    return null;
  }
}

function domainOf(value) {
  const url = safeUrl(value);
  if (!url) {
    return "";
  }
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return "";
  }
}

/* ------------------------------ comparators ------------------------------ */

function compareNames(a, b) {
  return (
    nameKey(a).localeCompare(nameKey(b), undefined, { sensitivity: "base" }) ||
    String(a.name || "").localeCompare(String(b.name || ""))
  );
}

const COMPARATORS = {
  name: compareNames,
  newest(a, b) {
    const dateA = parseAddedDate(a.date_added);
    const dateB = parseAddedDate(b.date_added);
    if (dateA && dateB && dateA.getTime() !== dateB.getTime()) {
      return dateB - dateA;
    }
    if (dateA && !dateB) {
      return -1;
    }
    if (!dateA && dateB) {
      return 1;
    }
    return compareNames(a, b);
  },
  popular(a, b) {
    return popularityScore(b) - popularityScore(a) || compareNames(a, b);
  },
  views(a, b) {
    return (
      toNumber(b.views) - toNumber(a.views) ||
      toNumber(b.clicks) - toNumber(a.clicks) ||
      compareNames(a, b)
    );
  },
};

/* -------------------------------- rendering ------------------------------ */

function formatCount(value) {
  return new Intl.NumberFormat(undefined, {
    notation: "compact",
    maximumFractionDigits: 1,
  }).format(toNumber(value));
}

function createChip(text, className, title) {
  const chip = document.createElement("span");
  chip.className = className ? `chip ${className}` : "chip";
  chip.textContent = text;
  if (title) {
    chip.title = title;
  }
  return chip;
}

function createCard(entry) {
  const item = document.createElement("li");
  item.className = "card";

  const heading = document.createElement("h3");
  heading.className = "card-title";
  const link = document.createElement("a");
  link.textContent = entry.name || entry.url || "Untitled portfolio";
  link.href = safeUrl(entry.url) || "#";
  link.target = "_blank";
  link.rel = "noopener noreferrer";
  const domain = domainOf(entry.url);
  if (domain) {
    const domainEl = document.createElement("span");
    domainEl.className = "domain";
    domainEl.textContent = domain;
    link.appendChild(domainEl);
  }
  heading.appendChild(link);
  item.appendChild(heading);

  if (entry.tagline) {
    const tagline = document.createElement("p");
    tagline.className = "card-tagline";
    tagline.textContent = entry.tagline;
    item.appendChild(tagline);
  }

  const meta = document.createElement("div");
  meta.className = "meta";

  const added = parseAddedDate(entry.date_added);
  if (added) {
    const label = new Intl.DateTimeFormat(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
      timeZone: "UTC",
    }).format(added);
    const time = document.createElement("time");
    time.dateTime = entry.date_added;
    time.title = `Added to the list on ${label}`;
    time.className = "chip chip-date";
    time.textContent = `Added ${label}`;
    meta.appendChild(time);
  }

  if (entry.views !== null && entry.views !== undefined) {
    const views = toNumber(entry.views);
    meta.appendChild(
      createChip(`${formatCount(views)} views`, null, `${views.toLocaleString()} views`),
    );
  }
  if (entry.clicks !== null && entry.clicks !== undefined) {
    const clicks = toNumber(entry.clicks);
    meta.appendChild(
      createChip(`${formatCount(clicks)} clicks`, null, `${clicks.toLocaleString()} clicks`),
    );
  }

  if (meta.childElementCount > 0) {
    item.appendChild(meta);
  }
  return item;
}

function sortLabel(option) {
  const selected = els.sortSelect.querySelector(`option[value="${option}"]`);
  return selected ? selected.textContent : option;
}

function updateStatus() {
  const shown = Math.min(renderedCount, sorted.length);
  const total = sorted.length.toLocaleString();
  els.status.textContent =
    shown === 0
      ? "No portfolios to show."
      : `Showing ${shown.toLocaleString()} of ${total} portfolios · sorted by ${sortLabel(currentSort)}`;
}

function sentinelVisible() {
  const rect = els.sentinel.getBoundingClientRect();
  return rect.top <= window.innerHeight + 600;
}

function renderNextPage() {
  if (renderedCount >= sorted.length) {
    els.sentinel.hidden = true;
    return;
  }
  els.sentinel.hidden = false;

  const fragment = document.createDocumentFragment();
  const end = Math.min(renderedCount + PAGE_SIZE, sorted.length);
  for (let index = renderedCount; index < end; index += 1) {
    fragment.appendChild(createCard(sorted[index]));
  }
  els.list.appendChild(fragment);
  renderedCount = end;
  updateStatus();

  if (renderedCount >= sorted.length) {
    els.sentinel.hidden = true;
  } else {
    requestAnimationFrame(() => {
      if (sentinelVisible()) {
        renderNextPage();
      }
    });
  }
}

function applySort(option) {
  currentSort = SORT_OPTIONS.includes(option) ? option : "name";
  sorted = portfolios.slice().sort(COMPARATORS[currentSort]);
  renderedCount = 0;
  els.list.replaceChildren();
  els.sortSelect.value = currentSort;
  renderNextPage();
  persistSort(currentSort);
}

function persistSort(option) {
  try {
    window.localStorage.setItem(STORAGE_KEY, option);
  } catch {
    /* private mode / storage disabled: sorting still works for this visit */
  }
  const url = new URL(window.location.href);
  if (option === "name") {
    url.searchParams.delete("sort");
  } else {
    url.searchParams.set("sort", option);
  }
  window.history.replaceState(null, "", url);
}

function sortFromLocation() {
  const requested = new URLSearchParams(window.location.search).get("sort");
  return requested && SORT_OPTIONS.includes(requested) ? requested : null;
}

function storedSort() {
  try {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    return stored && SORT_OPTIONS.includes(stored) ? stored : null;
  } catch {
    return null;
  }
}

function showError(error) {
  els.status.textContent = "Could not load the portfolio list.";
  els.error.hidden = false;
  els.error.textContent =
    `Could not load feed.json (${error.message}). ` +
    "If you opened this page as a local file, serve the repository over HTTP instead " +
    "(for example: python -m http.server) and visit http://localhost:8000/web/. " +
    "You can also regenerate the feed with: python src/generate_feed.py";
}

/* --------------------------------- startup ------------------------------- */

async function load() {
  try {
    const response = await fetch(FEED_URL, { cache: "no-cache" });
    if (!response.ok) {
      throw new Error(`HTTP ${response.status} ${response.statusText}`.trim());
    }
    const data = await response.json();
    if (!Array.isArray(data)) {
      throw new Error("feed.json does not contain a list of portfolios");
    }
    portfolios = data.filter((entry) => entry && typeof entry === "object");
    els.totalCount.textContent = portfolios.length.toLocaleString();

    const hasMetrics = portfolios.some(
      (entry) => entry.views !== null && entry.views !== undefined ||
        entry.clicks !== null && entry.clicks !== undefined ||
        entry.popularity !== null && entry.popularity !== undefined,
    );
    els.metricsNote.hidden = hasMetrics;

    els.sortSelect.addEventListener("change", (event) => applySort(event.target.value));
    applySort(sortFromLocation() || storedSort() || "name");
  } catch (error) {
    showError(error);
  }
}

load();
